version: "3.3"

services:
    postgres: 
      image: postgres:latest
      container_name: postgres
      ports:
        - 5432:5432
      volumes: 
        - ./docker/postgres/data:/var/lib/postgresql/data
      restart: always
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root

